Add bias and weight views
PumasAI/SimpleChains.jl pull request #85
Opened 2022-06-07 20:13 UTC by chriselrod

Fixes #83.

Layer types can overload
```julia
_getparams(::Val{paramtype}, layer, p, inputdim)
```
to specify different behavior, but currently I use some simple heuristics to define default methods that happen to cover all currently defined layer types.

2022-06-08 07:37 UTC, korsbo requested changes
The functionality seems good but the PR needs a little cleaning and the CI needs to pass.

2022-06-08 07:37 UTC, korsbo commented on src/utils.jl
> +_get(::Val{:weight}, x) where {A,B} = x
```suggestion
_get(::Val{:weight}, x) = x
```

2022-06-08 07:37 UTC, korsbo commented on src/utils.jl
> +@inline function _getparams(f::F, layer, p, inputdim) where {F}
```suggestion
@inline function _getparams(f, layer, p, inputdim)
```
`F` is not used - is the `where {F}` superfluous?

2022-06-08 07:37 UTC, korsbo commented on src/utils.jl
> +_get(::Val{:bias}, x) where {A,B} = nothing
```suggestion
_get(::Val{:bias}, x) = nothing
```

2022-06-08 07:37 UTC, korsbo commented on src/utils.jl
> +function _walk_chain(f::F, layers, p, inputdim) where {F}
```suggestion
function _walk_chain(f, layers, p, inputdim)
```

2022-06-08 07:37 UTC, korsbo commented on src/simple_chain.jl
> -=#
Why is this commented out here? It seems unrelated to the PR and I don't see whether there are any adverse effects of this.

2022-06-08 07:37 UTC, korsbo commented on src/utils.jl
> +  _get(f, A), p, outputdim
Would it make sense to add `layer` as an additional argument to `_get`? Then you could be explicit about for which layers the `(weights, biases)` assumption will hold and it would be easier for the next dev to grok what to do in order to extend support for new layer types.

2022-06-08 07:50 UTC, chriselrod commented on src/utils.jl
> +@inline function _getparams(f::F, layer, p, inputdim) where {F}
`F` is `::Val`, but originally I was thinking it could be a function.
If it's a function, it'd be needed to force specialization.

2022-06-08 07:50 UTC, chriselrod commented on src/simple_chain.jl
> -=#
It was already commented out. I'm just deleting it.

2022-06-08 07:51 UTC, chriselrod commented on src/utils.jl
> +  _get(f, A), p, outputdim
I guess we could have both `_getparams` and `_get` be overloadable points.

2022-06-08 09:34 UTC, korsbo commented on src/simple_chain.jl
> -=#
aah, my mistake. Leave it be

2022-06-08 09:38 UTC, korsbo commented on src/simple_chain.jl
> -=#
It does not currently add functionality but I think it would make the logic and assumptions more clear for other devs or our future selves.

2022-06-08 09:38 UTC, korsbo commented on src/utils.jl
> +  _get(f, A), p, outputdim
It does not currently add functionality but I think it would make the logic and assumptions more clear for other devs or our future selves.

2022-06-08 09:38 UTC, korsbo commented on src/utils.jl
> +@inline function _getparams(f::F, layer, p, inputdim) where {F}
Ok, I don't mind

2022-06-09 05:20 UTC, korsbo approved these changes

2022-06-09 07:19 UTC, korsbo commented
Bump version and tag release on merge?

2022-06-09 07:19 UTC, merged