Stack Memory
PumasAI/SimpleChains.jl pull request #97
Opened 2022-07-01 21:50 UTC by chriselrod

Before releasing, I ought to run a lot of benchmarks and add `@inline`s to make sure `StaticArray`s support is good.

2022-07-05 08:20 UTC, korsbo requested changes
Before going to the very scant meat of the review, I'll go a bit meta. I think this and other big or even medium-sized PRs might be improved by treating their descriptions like summaries that provide 
- Context - "Here, I'm increasing runtime performance by providing explicit stack memory management and thus reducing the overhead of memory transfer. This should be especially powerful in the case of XXX.". 
- Method - "This PR alters the previous memory management idea which was XXX and instead replace it with XXX". "To the best of my understanding, this should have no disadvantages but it enables XXX".
- Results - "A simple benchmark shows that XXX and that the PR achieves its goal with the only trade-offs being XXX. A more rigorous and public benchmark to be added in XXX in another PR (link to issue)". 

This would serve a few different purposes. 
- it would generate excitement from users who are not someone you might have asked to review but who is keeping an eye on PRs and recent updates because they're interested. Some context and some excitement goes a long way to embolden people to weigh in. After weighing in and receiving appreciative responses (even if only "That would not work because of XXX but it's really cool to see that someone cares enough about this work to read and comment. Positive/contructive engagement is always welcomed!"). Once engaged and also after having had positive interactions with the lead dev then the step to deeper contributions is reduced. 
- it would improve the public record of changes. The release notes link to the PR, so big and cool PRs are likely to actually be read. I know that I read the descriptions of merged PRs for packages that I follow closely enough to care about their releases. 
- Finally, It would provide the reviewer with some context and an immediate high-level overview of what's going on. It would also dangle the benefits of having this merged as a carrot for the reviewer to actually get 'round to review. 

If you want to just dump your current progress in the repo and benefit from CI without spending time on a description then you might make a draft PR and edit the top description before converting to a PR and requesting reviews. 

Right now, I'm lacking both a bit of context but also a fair bit of expertise and understanding of the codebase to provide very meaningful comments (I admit that only a small chunk of those missing pieces could be fixed by a description - one can make hard reviews easier but not easy.). All I can contribute here is some minor linting and some parroting of the concerns that CI is raising. There are some tests lacking and there is one failing CI test run. 

Fix the problem behind the failing CI, review codecovs complaints (there are some functions that look like they need tests; `train_unbatched_core`, for example) and after that, I don't see anything blocking even though a description for the public record would be a plus.

2022-08-27 03:42 UTC, mohamed82008 commented
Tests seem to fail on Julia 1.6 only.

2022-08-27 18:00 UTC, chriselrod commented
> Tests seem to fail on Julia 1.6 only.

That is tricky. SimpleChains relies a lot on recursion, which triggers heuristics in Julia's compiler to give up.
We can override these heuristics in Julia >=1.7
https://github.com/PumasAI/SimpleChains.jl/blob/d737d40fce5d5701d1eb1661158beec6c762c60f/src/SimpleChains.jl#L84-L93

2022-08-27 23:39 UTC, chriselrod commented
Tests now pass on 1.6.
Still need to add more tests, and some code is only run on 1.6 so it won't show up as covered when using `coverage=false` for 1.6...

2022-08-29 17:13 UTC, chriselrod commented
We could improve test coverage by dropping support for Julia 1.6, or by creating a small subset of tests to run with Julia 1.6 + enabled coverage.

2022-08-30 12:42 UTC, chriselrod commented on src/optimize.jl
> +  train_batched_core!(c, pu + offset, g, p, pX, opt, iters, leaveofflast, mpt, N_bs)
Tested.

2022-08-30 12:44 UTC, chriselrod commented on src/chain_rules.jl
> +    end
tested

2022-08-30 12:53 UTC, korsbo commented
What would we lose if we dropped LTS support? I imagine that the intersection of LTS users and SC users is currently rather small. However, not supporting LTS might prevent other packages from using SC as a dependency. Are there any natural future SC integrations (Flux, Lux, SciML, etc.) that would suffer from a lack of LTS support?

2022-09-01 15:54 UTC, chriselrod commented
I think that we should just live with two versions for now.

2022-09-01 17:49 UTC, mohamed82008 commented on src/activation.jl
> +  align(prod(s) * static_sizeof(T)), s
the 2 was dropped here, was this on purpose?

2022-09-01 17:49 UTC, mohamed82008 commented on src/chain_rules.jl
> +if isdefined(ChainRulesCore, :NoTangent)
is the `@static` no longer needed?

2022-09-01 17:51 UTC, mohamed82008 commented on src/chain_rules.jl
> +if isdefined(ChainRulesCore, :NoTangent)
perhaps this whole branch is not needed anymore if we support the latest ChainRulesCore versions only.

2022-09-01 17:52 UTC, chriselrod commented on src/activation.jl
> +  align(prod(s) * static_sizeof(T)), s
Yes. The 2 came from forward + reverse, while `forward_layer_output_size` is forwad only.

2022-09-01 17:53 UTC, chriselrod commented on src/chain_rules.jl
> +if isdefined(ChainRulesCore, :NoTangent)
`@static` is only really needed if you have invalid syntax hiding behind a branch, or it may be nice inside a function.
Top level in a package should be interpreted anyway.

2022-09-01 20:11 UTC, mohamed82008 commented on src/memory.jl
> +  length(heap_memory) >= num_bytes || resize!(empty!(heap_memory), Int(num_bytes))
why empty and then resize?

2022-09-01 20:12 UTC, mohamed82008 commented on src/memory.jl
> +  if num_bytes <= 16384
should this number be a customisable global constant?

2022-09-01 20:14 UTC, mohamed82008 commented on src/memory.jl
> +  output_size(Val(T), layers, sx) + additional + static(63)
could you add a comment here? why 63?

2022-09-01 20:18 UTC, mohamed82008 commented on src/optimize.jl
> +    Δxᵢ = mt[i] / ((1 - βp₁) * (sqrt(vt[i] / (1 - βp₂)) + 1.0f-8))
should the 1.0f-8 be `eps(eltype(Δ))` instead?

2022-09-01 20:26 UTC, chriselrod commented on src/memory.jl
> +  length(heap_memory) >= num_bytes || resize!(empty!(heap_memory), Int(num_bytes))
If there isn't enough contiguous space following the current allocation, `resize!` allocates new memory, and copies the old memory there before discarding the old.
We don't care about the memory, and thus don't want to copy any of it.

I'm not sure if `empty!` actually helps, but it at least communicates the idea.

2022-09-01 20:28 UTC, chriselrod commented on src/memory.jl
> +  if num_bytes <= 16384
Good idea.

2022-09-01 20:31 UTC, chriselrod commented on src/memory.jl
> +  if num_bytes <= 16384
By customizable, do you mean use `Preferences.jl`?

2022-09-01 20:36 UTC, chriselrod commented on src/optimize.jl
> +    Δxᵢ = mt[i] / ((1 - βp₁) * (sqrt(vt[i] / (1 - βp₂)) + 1.0f-8))
I'm not sure. In Flux, it's `1e-8` (a `Float64`), but allows users to customize it. It doesn't automatically change based on element type, but it may assume `Float32` is used in general more than we do.

2022-09-01 20:37 UTC, chriselrod commented on src/memory.jl
> +  output_size(Val(T), layers, sx) + additional + static(63)
We want to 64 byte align the pointers, so we add 63 extra bytes to make sure that we can offset the pointer to achieve 64 byte alignment.
That is, worse case scenario we get a pointer that is `+1` with respect to a 64 byte boundary. We can then add 63 to get a multiple of 64.

2022-09-01 20:38 UTC, chriselrod commented on src/memory.jl
> +  output_size(Val(T), layers, sx) + additional + static(63)
Realistically, the pointers we're getting are probably going to be at least 16 byte aligned, meaning we probably don't need to add anything more than 48 to get 64.

2022-09-01 20:39 UTC, chriselrod commented on src/memory.jl
> +  output_size(Val(T), layers, sx) + additional + static(63)
Memory reads/writes that cross a 64 byte boundary cost double.
AVX512 reads/writes up to 64 bytes at a time, meaning either 0% or 100% of reads/writes cross such a boundary.

2022-09-01 20:40 UTC, chriselrod commented on src/memory.jl
> +  output_size(Val(T), layers, sx) + additional + static(63)
It is also these boundaries that get fetched by the prefetcher. If you're going across a boundary, you need to fetch 128 bytes worth of memory (the 64 byte blocks, aka cachelies, on both sides of that boundary)

2022-09-01 20:42 UTC, chriselrod commented on src/memory.jl
> +  output_size(Val(T), layers, sx) + additional + static(63)
This second case doesn't matter if you're streaming through memory, as then you probably needed both blocks anyway.
But it can be important if you're moving across the columns of a matrix, for exmaple.

2022-09-01 20:43 UTC, mohamed82008 commented on src/memory.jl
> +  if num_bytes <= 16384
ya or environment variable or even just a global constant for now at the top of the module and then something more fancy can be done in another PR

2022-09-01 20:45 UTC, mohamed82008 commented on src/memory.jl
> +  output_size(Val(T), layers, sx) + additional + static(63)
I see. Thanks for the explanation. Most of it went over my head but adding the comment is useful anyways.

2022-09-01 20:45 UTC, chriselrod commented on src/memory.jl
> +  output_size(Val(T), layers, sx) + additional + static(63)
There's more SimpleChains can do with internal memory management/representation, but I've kept things relatively simple so far.

That is, padding to maintain alignment of columns of a matrix comes at the cost of making it so that you can no longer linearly index the array. Which means figuring out if that's really worthwhile.

Matrices with misaligned columns (i.e., matrices number of rows that aren't a multiple of a number like 8 or 16) aren't going to benefit from this alignment during operations like matrix multiplication, but it'll help those matrices when we do things like calculate penalties...
But for internal outputs, I should probably experiment with different representations.

2022-09-01 20:46 UTC, mohamed82008 commented on src/memory.jl
> +  length(heap_memory) >= num_bytes || resize!(empty!(heap_memory), Int(num_bytes))
I see. Thanks for the explanation.

2022-09-01 20:51 UTC, chriselrod commented on src/memory.jl
> +  output_size(Val(T), layers, sx) + additional + static(63)
> Most of it went over my head but adding the comment is useful anyways.

The TLDR is that memory is is divided up into blocks called "cachelines", it's more expensive to work with multiple cachelines at a time.
By offsetting our pointers to one of these cacheline boundaries, we can make it more likely that we work within a cacheline boundary.

For example:
```julia
julia> function squared_norm(x)
           s = zero(eltype(x))
           @simd for i = eachindex(x)
               s += x[i]
           end
           s
       end
squared_norm (generic function with 1 method)

julia> x = rand(257);

julia> Int(pointer(x)) % 64
0

julia> @btime squared_norm(@view($x[begin:end-1]))
  11.219 ns (0 allocations: 0 bytes)
124.962370757488

julia> @btime squared_norm(@view($x[begin+1:end]))
  35.809 ns (0 allocations: 0 bytes)
125.24915615899357
```

2022-09-01 20:53 UTC, chriselrod commented on src/memory.jl
> +  output_size(Val(T), layers, sx) + additional + static(63)
Note in both cases it's 256 elements. In the first case, the pointer is aligned to 64 bytes (the remainder is 0), while in the second case, we offset by `1`, throwing off the alignment, making the memory reads more expensive.
```julia
julia> Int(pointer(@view(x[begin:end-1]))) % 64
0

julia> Int(pointer(@view(x[begin+1:end]))) % 64
8
```

2022-09-01 20:56 UTC, chriselrod commented on src/memory.jl
> +  output_size(Val(T), layers, sx) + additional + static(63)
Does that make more sense/seeing the benchmark help?

Note that on the M1 Mac, the cachelines are actually 128 bytes (2x larger), while the register size is 16 bytes (4x smaller), so loading/storing across such a boundary is going to be a much smaller issue on your computer than it is mine.

2022-09-01 21:05 UTC, mohamed82008 commented on src/memory.jl
> +  output_size(Val(T), layers, sx) + additional + static(63)
Thanks for the explanation. Ya I get the gist of it. Makes me wonder if this kind of functionality should just go into an array package that allows itself to be C-incompatible semantically by doing tricks like this to achieve more performance, e.g. doing column-wise alignment and padding as necessary. You had a package like this I believe. Might be useful to hide these details there instead.

2022-09-01 21:10 UTC, mohamed82008 commented on src/memory.jl
> +  output_size(Val(T), layers, sx) + additional + static(63)
Your code often feels like you are programming in 2-3 levels of abstraction simultaneously :) My brain can only handle 1-1.5 levels at a time usually depending on how long I stare at the code. 2 is pushing it. I am always learning something new from reviewing your code though which probably means I shouldn't be the one doing the review 😆

2022-09-01 22:00 UTC, mohamed82008 commented on test/layer_tests.jl
> +  @test gz ≈ g rtol=1e-6
would be nice to compare against finite difference or something that doesn't use the rrules defined in the package

2022-09-01 22:02 UTC, mohamed82008 commented
I don't feel qualified enough to approve this PR but if tests pass, let's go ahead and merge it and make an alpha release so we can test this package more downstream.

2022-09-01 23:28 UTC, chriselrod commented on test/layer_tests.jl
> +  @test gz ≈ g rtol=1e-6
True.
There are a few tests using `ForwardDiff`, but some of those also hit the `ForwardDiff.Dual` methods defined here.

2022-09-01 23:51 UTC, chriselrod commented
> I don't feel qualified enough to approve this PR

Well, it's a problem if no one is!

The implementations in this library are supposed to be "simple" in at least the sense that it's hopefully not too difficult to guess what the assembly will look, and everything the CPU is actually going to have to do to execute your code (at least if you know what LoopVectorization.jl is likely to do when presented with a given loop, which probably only I do).
In this sense, it's a lot less opaque than something like Flux.jl, which can achieve miraculous amounts of allocations and the associated bad performance out of nowhere from very few lines of code.

Perhaps there's a sort of declarative vs imperative-like tradeoff in readability, where some code makes the former/what easier to infer, and other code makes the latter/the how easier.

It might be interesting to document any "tricks" this library uses to make it easier for others to get into and modify to suite their purposes, or serve as educational material.
It may also serve to reveal things that should be abstracted out, like the `+ static(63)` probably should be.
I do think someone else with enough time may be able to take a stab at it by just asking questions, like you did here.

I've also been considering taking a machine learning course and writing up NN-related exercises as SimpleChains.jl tutorials (and fix/add support for things it needs).

2022-09-01 23:54 UTC, chriselrod commented on src/memory.jl
> +  output_size(Val(T), layers, sx) + additional + static(63)
That's a polite way to say "your code is an illegible mess" lol

I think the `+ static(63)` and alignment should probably all be moved to the allocation functions, rather than being a part of the "how much to allocate" functions.

`PaddedMatrices` was that library, but it was superseded by `StrideArrays`.
SimpleChains already depends on `StrideArraysCore`. I will probably add support for things like automatically padding again.

2022-09-02 00:06 UTC, mohamed82008 commented
I would love to volunteer for that job as I am sure it will be educational but my hands are currently full between the work at Pumas and the hobby projects I am desperately trying to keep alive like TopOpt.jl and Nonconvex.jl. Perhaps we can internally discuss allocating more of my Pumas time here. Let's see. Alternatively if someone else comes along, we can also try to provide funding for that kind of work.

2022-09-02 09:38 UTC, korsbo approved these changes

2022-09-02 10:23 UTC, merged

2022-09-02 10:58 UTC, korsbo commented
🎉